---
title: "Draft Fidelity"
author: "Jiun Lee"
date: "2022-10-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(tidyr)
imdb <- read.csv("/Users/jiunlee/MSSP22/Fidelity/IMDB Dataset.csv")
imdb <- imdb %>% select(-sentiment)
# avector <- as.vector(imdb['review']) #sublist
# class(avector) 
# 
# avector <- imdb[['review']] #atomic column
# class(avector)

# textv <- imdb[,1]: vector
text_df <- tibble(review = 1:50000, sentence = imdb[,1]) 
```


#tokenizing by bigram
```{r}
library(tokenizers)
library(tidytext)
token_bigram <- text_df %>% unnest_tokens(bigram, sentence, token = "ngrams", n = 2) %>% 
  count(review,bigram,sort = TRUE)

# freq_bigram <- token_bigram %>% count(bigram,sort = TRUE)

total_bigram <- token_bigram %>% 
  group_by(review) %>% 
  summarize(total = sum(n))

review_bigram <- left_join(token_bigram, total_bigram)

#Zipf’s law states that the frequency that a word appears is inversely proportional to its rank.
freq_by_rank_bi <- review_bigram %>% 
  group_by(review) %>% 
  mutate(rank = row_number(), 
         `term frequency` = n/total) %>%
  ungroup()

#ggplot
freq_by_rank_bi %>% 
  ggplot(aes(rank, `term frequency`, color = review)) + 
  geom_line(size = 1.1, alpha = 0.8, show.legend = FALSE) + 
  scale_x_log10() +
  scale_y_log10()
```

#tf-idf
```{r}
review_tf_idf_bi <- review_bigram %>%
  bind_tf_idf(bigram, review, n)

#look at terms with high tf-idf in reviews.
review_tf_idf_bi %>%
  select(-total) %>%
  arrange(desc(tf_idf))

#too many 'br br' -> let's remove 'br br'
review_separated <- review_bigram %>%  
  separate(bigram, into = c("word1", "word2"), sep = " ")

review_united <- review_separated %>%
  filter(!word1 %in% c('br','of','the','is'),
         !word2 %in% c('br','of','the','is')) %>%
  unite(bigram, c(word1, word2), sep = " ")

#resume tf-idf
review_tf_idf_bi2 <- review_united %>%
  bind_tf_idf(bigram, review, n)

review_tf_idf_bi2 

#look at terms with high tf-idf in reviews.
review_tf_idf_bi2 %>%
  select(-total) %>%
  arrange(desc(tf_idf))

library(ggplot2)
library(forcats)

review_tf_idf_bi2 %>%
  group_by(review) %>%
  slice_max(tf_idf, n = 15) %>%
  ungroup() %>%
  ggplot(aes(tf_idf, fct_reorder(bigram, tf_idf), fill = review)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~review, ncol = 2, scales = "free") +
  labs(x = "tf-idf", y = NULL)


words_tf_idf <- review_united %>%
  review_tf_idf_bi2
  group_by(review) %>% 
  top_n(10) %>%
  ungroup() %>% 
  facet_bar(y = bigram, x = tf_idf, by = review, ncol = 3) + 
  labs(title = "Top 10 words picked tf-idf")




```




```{r}


```



```{r}


```


```{r}


```

```{r}


```